apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:dev, applications, get, *, allow
    p, role:dev, applications, sync, *, allow
    p, role:dev, applications, update, *, allow
    p, role:dev, applications, override, *, allow
    p, role:dev, clusters, get, *, allow
    p, role:dev, repositories, get, *, allow
    p, role:dev, logs, get, *, allow
    
    g, pedAujo, role:dev
    g, brunEira, role:dev    
    
    p, role:noLogs, applications, get, *, allow
    p, role:noLogs, clusters, get, *, allow

    g, visitor, role:noLogs

    g, jaminUavre, role:admin
    g, LaVorce, role:admin
    g, CeeAhuja, role:admin
    g, cedChi, role:admin
    g, roRvM, role:admin
    

# https://github.com/argoproj/argo-cd/issues/7211